import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    const now = knex.fn.now();

    const rows = [
        {
            name: 'dashboard:read',
            module: 'dashboard',
            action: 'read',
            label: 'Lihat Dashboard',
            description: 'Mengakses halaman dashboard.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },

        {
            name: 'village:create',
            module: 'village',
            action: 'create',
            label: 'Tambah Desa',
            description: 'Membuat data desa baru.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'village:read',
            module: 'village',
            action: 'read',
            label: 'Lihat Desa',
            description: 'Melihat daftar dan detail desa.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'village:update',
            module: 'village',
            action: 'update',
            label: 'Ubah Desa',
            description: 'Mengubah data desa.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'village:delete',
            module: 'village',
            action: 'delete',
            label: 'Hapus Desa',
            description: 'Menghapus data desa.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },

        {
            name: 'user:create',
            module: 'user',
            action: 'create',
            label: 'Tambah User',
            description: 'Membuat user baru.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'user:read',
            module: 'user',
            action: 'read',
            label: 'Lihat User',
            description: 'Melihat daftar dan detail user.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'user:update',
            module: 'user',
            action: 'update',
            label: 'Ubah User',
            description: 'Mengubah data user.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'user:delete',
            module: 'user',
            action: 'delete',
            label: 'Hapus User',
            description: 'Menghapus data user.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },

        {
            name: 'role:read',
            module: 'role',
            action: 'read',
            label: 'Lihat Role',
            description: 'Melihat daftar role.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'role:assign',
            module: 'role',
            action: 'assign',
            label: 'Assign Role',
            description: 'Memberikan role ke user.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },

        {
            name: 'permission:read',
            module: 'permission',
            action: 'read',
            label: 'Lihat Permission',
            description: 'Melihat daftar permission.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
        {
            name: 'permission:assign',
            module: 'permission',
            action: 'assign',
            label: 'Assign Permission',
            description: 'Memberikan permission ke role.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },

        {
            name: 'report:read',
            module: 'report',
            action: 'read',
            label: 'Lihat Laporan',
            description: 'Melihat laporan sistem.',
            is_system: true,
            status: 'active',
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: now,
            updated_at: now,
            deleted_at: null,
        },
    ];

    await knex('auth_permission')
        .insert(rows)
        .onConflict('name')
        .merge({
            module: knex.raw('excluded.module'),
            action: knex.raw('excluded.action'),
            label: knex.raw('excluded.label'),
            description: knex.raw('excluded.description'),
            is_system: knex.raw('excluded.is_system'),
            status: knex.raw('excluded.status'),
            updated_at: now,
            deleted_at: null,
        });
}